// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "codes/actions.proto" (package "protos", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum protos.ActionsEnum
 */
export enum ActionsEnum {
    /**
     * @generated from protobuf enum value: HEALTH_CHECK = 0;
     */
    HEALTH_CHECK = 0,
    /**
     * @generated from protobuf enum value: NEW_SESSION = 1;
     */
    NEW_SESSION = 1,
    /**
     * @generated from protobuf enum value: DOWNLOAD_VIDEO_AUDIO = 2;
     */
    DOWNLOAD_VIDEO_AUDIO = 2,
    /**
     * @generated from protobuf enum value: DOWNLOAD_VIDEO = 3;
     */
    DOWNLOAD_VIDEO = 3,
    /**
     * @generated from protobuf enum value: DOWNLOAD_AUDIO = 4;
     */
    DOWNLOAD_AUDIO = 4,
    /**
     * @generated from protobuf enum value: LIST_FILES = 5;
     */
    LIST_FILES = 5,
    /**
     * @generated from protobuf enum value: RETRIEVE_FILE = 6;
     */
    RETRIEVE_FILE = 6,
    /**
     * @generated from protobuf enum value: DELETE_FILE = 7;
     */
    DELETE_FILE = 7,
    /**
     * @generated from protobuf enum value: DELETE_SESSION = 8;
     */
    DELETE_SESSION = 8
}
