// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "codes/errors.proto" (package "protos", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum protos.ErrorsEnum
 */
export enum ErrorsEnum {
    /**
     * @generated from protobuf enum value: MALFORMED_MESSAGE = 0;
     */
    MALFORMED_MESSAGE = 0,
    /**
     * @generated from protobuf enum value: NOT_RECOGNIZED = 1;
     */
    NOT_RECOGNIZED = 1,
    /**
     * @generated from protobuf enum value: FOLDER_ALREADY_EXISTS = 2;
     */
    FOLDER_ALREADY_EXISTS = 2,
    /**
     * @generated from protobuf enum value: FAILED_DOWNLOAD = 3;
     */
    FAILED_DOWNLOAD = 3,
    /**
     * @generated from protobuf enum value: FAILED_LISTING_FILES = 4;
     */
    FAILED_LISTING_FILES = 4,
    /**
     * @generated from protobuf enum value: FAILED_DELETE_FILE = 5;
     */
    FAILED_DELETE_FILE = 5,
    /**
     * @generated from protobuf enum value: FAILED_DELETE_SESSION = 6;
     */
    FAILED_DELETE_SESSION = 6,
    /**
     * @generated from protobuf enum value: NO_ITEMS_PRESENT = 7;
     */
    NO_ITEMS_PRESENT = 7,
    /**
     * @generated from protobuf enum value: CATASTROPHIC_ERROR = 8;
     */
    CATASTROPHIC_ERROR = 8
}
