// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "codes/prefix.proto" (package "protos", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum protos.PrefixesEnum
 */
export enum PrefixesEnum {
    /**
     * @generated from protobuf enum value: ACTION = 0;
     */
    ACTION = 0,
    /**
     * @generated from protobuf enum value: SUCCESS = 1;
     */
    SUCCESS = 1,
    /**
     * @generated from protobuf enum value: ERROR = 2;
     */
    ERROR = 2
}
