// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "codes/success.proto" (package "protos", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum protos.SuccessEnum
 */
export enum SuccessEnum {
    /**
     * @generated from protobuf enum value: SESSION_ID = 0;
     */
    SESSION_ID = 0,
    /**
     * @generated from protobuf enum value: VIDEO_DOWNLOADABLE = 1;
     */
    VIDEO_DOWNLOADABLE = 1,
    /**
     * @generated from protobuf enum value: LISTED_FILES = 2;
     */
    LISTED_FILES = 2,
    /**
     * @generated from protobuf enum value: READY_TO_SEND = 3;
     */
    READY_TO_SEND = 3,
    /**
     * @generated from protobuf enum value: DELETED_FILE = 4;
     */
    DELETED_FILE = 4,
    /**
     * @generated from protobuf enum value: SESSION_DELETE = 5;
     */
    SESSION_DELETE = 5,
    /**
     * @generated from protobuf enum value: SESSION_FOLDER_CREATED = 6;
     */
    SESSION_FOLDER_CREATED = 6
}
