// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.9
// source: codes/prefix.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrefixesEnum int32

const (
	PrefixesEnum_ACTION  PrefixesEnum = 0
	PrefixesEnum_SUCCESS PrefixesEnum = 1
	PrefixesEnum_ERROR   PrefixesEnum = 2
)

// Enum value maps for PrefixesEnum.
var (
	PrefixesEnum_name = map[int32]string{
		0: "ACTION",
		1: "SUCCESS",
		2: "ERROR",
	}
	PrefixesEnum_value = map[string]int32{
		"ACTION":  0,
		"SUCCESS": 1,
		"ERROR":   2,
	}
)

func (x PrefixesEnum) Enum() *PrefixesEnum {
	p := new(PrefixesEnum)
	*p = x
	return p
}

func (x PrefixesEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrefixesEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_codes_prefix_proto_enumTypes[0].Descriptor()
}

func (PrefixesEnum) Type() protoreflect.EnumType {
	return &file_codes_prefix_proto_enumTypes[0]
}

func (x PrefixesEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrefixesEnum.Descriptor instead.
func (PrefixesEnum) EnumDescriptor() ([]byte, []int) {
	return file_codes_prefix_proto_rawDescGZIP(), []int{0}
}

var file_codes_prefix_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51231,
		Name:          "protos.name",
		Tag:           "bytes,51231,opt,name=name",
		Filename:      "codes/prefix.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string name = 51231;
	E_Name = &file_codes_prefix_proto_extTypes[0]
)

var File_codes_prefix_proto protoreflect.FileDescriptor

var file_codes_prefix_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x47,
	0x0a, 0x0c, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x11,
	0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x1a, 0x05, 0xfa, 0x81, 0x19, 0x01,
	0x41, 0x12, 0x12, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x1a, 0x05,
	0xfa, 0x81, 0x19, 0x01, 0x53, 0x12, 0x10, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02,
	0x1a, 0x05, 0xfa, 0x81, 0x19, 0x01, 0x45, 0x3a, 0x3a, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x9f, 0x90, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_codes_prefix_proto_rawDescOnce sync.Once
	file_codes_prefix_proto_rawDescData = file_codes_prefix_proto_rawDesc
)

func file_codes_prefix_proto_rawDescGZIP() []byte {
	file_codes_prefix_proto_rawDescOnce.Do(func() {
		file_codes_prefix_proto_rawDescData = protoimpl.X.CompressGZIP(file_codes_prefix_proto_rawDescData)
	})
	return file_codes_prefix_proto_rawDescData
}

var file_codes_prefix_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_codes_prefix_proto_goTypes = []interface{}{
	(PrefixesEnum)(0),                     // 0: protos.PrefixesEnum
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_codes_prefix_proto_depIdxs = []int32{
	1, // 0: protos.name:extendee -> google.protobuf.EnumValueOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codes_prefix_proto_init() }
func file_codes_prefix_proto_init() {
	if File_codes_prefix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_codes_prefix_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_codes_prefix_proto_goTypes,
		DependencyIndexes: file_codes_prefix_proto_depIdxs,
		EnumInfos:         file_codes_prefix_proto_enumTypes,
		ExtensionInfos:    file_codes_prefix_proto_extTypes,
	}.Build()
	File_codes_prefix_proto = out.File
	file_codes_prefix_proto_rawDesc = nil
	file_codes_prefix_proto_goTypes = nil
	file_codes_prefix_proto_depIdxs = nil
}
