package constants

const (
	CODE_ACTION_LETTER        = "A"
	CODE_HEALTH_CHECK         = "A0000"
	CODE_SESSION_ID           = "A0001"
	CODE_DOWNLOAD_VIDEO_AUDIO = "A1001"
	CODE_DOWNLOAD_VIDEO       = "A1002"
	CODE_DOWNLOAD_AUDIO       = "A1003"

	CODE_LIST_FILES = "A2000"
	CODE_GET_FILE   = "A2001"

	CODE_ERROR_LETTER                = "E"
	CODE_ERROR_MALFORMED_MESSAGE     = "E0000"
	CODE_ERROR_CODE_NOT_RECOGNIZED   = "E0001"
	CODE_ERROR_FOLDER_ALREADY_EXISTS = "E0002"
	CODE_ERROR_DOWNLOAD_FAILED       = "E0003"
	CODE_ERROR_FAILED_LISTING_FILES  = "E0004"

	CODE_SUCCESS_LETTER             = "S"
	CODE_SUCCESS_VIDEO_DOWNLOADABLE = "S0001"
	CODE_SUCCESS_LISTED_FILES       = "S0002"
)
